spring:
  profiles:
    active:
      - development
    group:
      development:
        - common
        - development_database
        - port_8080
      production-1:
        - common
        - production_database
        - port_9001
      production-2:
        - common
        - production_database
        - port_9002

---

spring:
  config:
    activate:
      on-profile: common

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      accessKey: ${BUCKET_ACCESSKEY}
      secretKey: ${BUCKET_SECRETKEY}
    region:
      static: ${BUCKET_REGION}
      auto: ${BUCKET_REGION_AUTO}
    stack:
      auto: ${BUCKET_STACK}

---

spring:
  config:
    activate:
      on-profile: development_database
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    sql.init.mode: alway
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


---

spring:
  config:
    activate:
      on-profile: production_database
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: port_8080

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: port_9001

server:
  port: 9001

---

spring:
  config:
    activate:
      on-profile: port_9002

server:
  port: 9002